#!/bin/bash
# AI 痕迹扫描脚本
# 用途：交付前扫描所有文件中的 AI 相关关键词
# 用法：bash harness/delivery/ai_scan.sh <delivery_dir>
#
# 注意：bash 3.x 兼容（macOS 默认）
# 对 .docx 文件会解压后扫描 XML 内容

set -e

DELIVERY_DIR="${1:-.}"
FOUND=0
TEXT_FILE_LIST=""
DOCX_FILE_LIST=""
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# 优先从 delivery_config.yaml 读取关键词，fallback 到硬编码
KEYWORDS=""
if [ -f "$SCRIPT_DIR/read_config.sh" ]; then
    . "$SCRIPT_DIR/read_config.sh"
    KEYWORDS="$(config_get_keywords)"
fi
if [ -z "$KEYWORDS" ]; then
    KEYWORDS="Claude|ChatGPT|GPT-4|GPT-3|Copilot|AI-generated|AI生成|语言模型|大模型|language model|LLM|artificial intelligence|generated by AI|assisted by AI|powered by AI|Anthropic|OpenAI|Co-Authored-By|noreply@anthropic"
fi

cleanup() {
    [ -n "$TEXT_FILE_LIST" ] && [ -f "$TEXT_FILE_LIST" ] && rm -f "$TEXT_FILE_LIST"
    [ -n "$DOCX_FILE_LIST" ] && [ -f "$DOCX_FILE_LIST" ] && rm -f "$DOCX_FILE_LIST"
}

trap cleanup EXIT

echo "=== AI 痕迹扫描 ==="
echo "扫描目录: $DELIVERY_DIR"
echo ""

if [ ! -d "$DELIVERY_DIR" ]; then
    echo "ERROR: 目录不存在: $DELIVERY_DIR"
    exit 1
fi

TEXT_FILE_LIST="$(mktemp -t ai_scan_text)"
DOCX_FILE_LIST="$(mktemp -t ai_scan_docx)"

# --- 扫描普通文本文件 ---
echo "--- 扫描文本文件 ---"
find "$DELIVERY_DIR" -type f \
    ! -name "._*" \
    \( -name "*.txt" -o -name "*.md" -o -name "*.R" -o -name "*.py" -o -name "*.sh" \
       -o -name "*.csv" -o -name "*.tsv" -o -name "*.html" -o -name "*.xml" \
       -o -name "*.json" -o -name "*.yaml" -o -name "*.yml" \) \
    -print > "$TEXT_FILE_LIST"

if [ -s "$TEXT_FILE_LIST" ]; then
    while IFS= read -r f; do
        [ -z "$f" ] && continue
        if grep -q -i -E "$KEYWORDS" "$f" 2>/dev/null; then
            if [ "$FOUND" -eq 0 ]; then
                echo "发现 AI 关键词的文件："
            fi
            echo "  !! $f"
            grep -n -i -E "$KEYWORDS" "$f" 2>/dev/null | head -5 | while IFS= read -r line; do
                echo "     $line"
            done
            FOUND=$((FOUND + 1))
        fi
    done < "$TEXT_FILE_LIST"
fi

if [ "$FOUND" -eq 0 ]; then
    echo "  文本文件: 清洁"
fi

# --- 扫描 .docx 文件（解压后扫描 XML） ---
echo ""
echo "--- 扫描 Word 文档 ---"
find "$DELIVERY_DIR" -type f ! -name "._*" -name "*.docx" -print > "$DOCX_FILE_LIST"

if [ ! -s "$DOCX_FILE_LIST" ]; then
    echo "  未发现 .docx 文件"
else
    while IFS= read -r docx; do
        local_tmpdir=""
        [ -z "$docx" ] && continue
        local_tmpdir="$(mktemp -d -t ai_scan_unzip)"
        if ! unzip -q -o "$docx" -d "$local_tmpdir" >/dev/null 2>&1; then
            echo "  !! 无法解压 $docx（可能已损坏/加密），视为不安全"
            FOUND=$((FOUND + 1))
            rm -rf "$local_tmpdir"
            continue
        fi

        if grep -q -r -i -E "$KEYWORDS" "$local_tmpdir" 2>/dev/null; then
            echo "  !! 发现 AI 关键词: $docx"
            grep -r -i -E "$KEYWORDS" "$local_tmpdir" 2>/dev/null | head -5 | while IFS= read -r line; do
                echo "     $line"
            done
            FOUND=$((FOUND + 1))
        else
            echo "  $docx: 清洁"
        fi

        rm -rf "$local_tmpdir"
    done < "$DOCX_FILE_LIST"
fi

echo ""
echo "=== 扫描结果 ==="
if [ "$FOUND" -gt 0 ]; then
    echo "FAILED: 发现 AI 痕迹！必须清理后才能交付。"
    exit 1
fi

echo "PASSED: 未发现 AI 痕迹，可以交付。"
exit 0
